/**
 * Canonical names for audit log entries.
 * Keep these stable — analytics queries and dashboards depend on the strings.
 */
export const AuditAction = {
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_LOGIN_FAILED: 'AUTH_LOGIN_FAILED',
  AUTH_REGISTER: 'AUTH_REGISTER',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  AUTH_GOOGLE: 'AUTH_GOOGLE',

  USER_UPDATE_SELF: 'USER_UPDATE_SELF',
  USER_DELETE_SELF: 'USER_DELETE_SELF',

  RUN_CREATE: 'RUN_CREATE',
  RUN_CANCEL: 'RUN_CANCEL',
  RUN_FAIL: 'RUN_FAIL',
  RUN_SUCCESS: 'RUN_SUCCESS',

  SESSION_CREATE: 'SESSION_CREATE',
  SESSION_DELETE: 'SESSION_DELETE',
  SESSION_ARCHIVE: 'SESSION_ARCHIVE',

  SUB_SUBSCRIBE: 'SUB_SUBSCRIBE',
  SUB_CANCEL: 'SUB_CANCEL',
  SUB_UPGRADE: 'SUB_UPGRADE',

  TEMPLATE_CREATE: 'TEMPLATE_CREATE',
  TEMPLATE_APPROVE: 'TEMPLATE_APPROVE',
  TEMPLATE_REJECT: 'TEMPLATE_REJECT',
  TEMPLATE_DELETE: 'TEMPLATE_DELETE',

  ADMIN_USER_SUSPEND: 'ADMIN_USER_SUSPEND',
  ADMIN_USER_UNSUSPEND: 'ADMIN_USER_UNSUSPEND',
  ADMIN_USER_DELETE: 'ADMIN_USER_DELETE',
  ADMIN_USER_PLAN_CHANGE: 'ADMIN_USER_PLAN_CHANGE',
  ADMIN_USER_ROLE_CHANGE: 'ADMIN_USER_ROLE_CHANGE',
  ADMIN_RUN_CANCEL: 'ADMIN_RUN_CANCEL',

  APIKEY_CREATE: 'APIKEY_CREATE',
  APIKEY_REVOKE: 'APIKEY_REVOKE',
} as const;

export type AuditAction = (typeof AuditAction)[keyof typeof AuditAction];
